### PR TITLE
Revert to without source generation

### PR DESCRIPTION
**Pull request by jlee671**
Source generator is causing problem for Roslyn Analyzer and since we aren't using trim anymore, we can delete this. Reverting back to before we added it, reference: https://github.com/microsoft/VSConfigFinder/pull/17/files#:~:text=var-,serializerOptions,-%3D%20new%20JsonSerializerOptions%20%7B

Pipeline Success: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7417292&view=results

Manual testing scenario: root level, sub level, multiple same levels tested both file and command line

### CODE REVIEW

**Review by tydunkel — APPROVED** [review]

**Comment by skylarnam** [comment]
Can you add a quick blurb about testing?

**Comment by jlee671** [comment]
> Can you add a quick blurb about testing?

Compliance build testing or VSConfigFinder functionality testing?

**Comment by skylarnam** [comment]
> > Can you add a quick blurb about testing?
> 
> Compliance build testing or VSConfigFinder functionality testing?

Both :) 
1. About the change fixing the compliance build
2. Testing core scenarios to verify the tool still behaves the same

**Comment by jlee671** [comment]
Just added test blurbs and pushed empty comment for build

**Review by skylarnam — APPROVED** [review]

**Review by skylarnam — APPROVED** [review]

**Pull request merged**
