### PR TITLE
Add support for publishing a single file executable

### PR DESCRIPTION
**Pull request by skylarnam**
We need to make sure to publish a single file executable for signing.

### CODE REVIEW

**Comment by tydunkel** [comment]
Did you want to add the publish step to the builds now, or plan on doing that later?

**Comment by skylarnam** [comment]
> Did you want to add the publish step to the builds now, or plan on doing that later?

I wanted to add that in a separate PR, since we don't have a clear idea how to do the signing step yet and I believe those two changes will be made in the same file, right?

**Comment by tydunkel** [comment]
> > Did you want to add the publish step to the builds now, or plan on doing that later?
> 
> I wanted to add that in a separate PR, since we don't have a clear idea how to do the signing step yet and I believe those two changes will be made in the same file, right?

Either way is fine, I don't expect much to change in the build when signing happens vs. just a publish now

**Review by tydunkel — APPROVED** [review]
LGTM

**Review by tydunkel — APPROVED** [review]

**Pull request merged**
